server.port=5003
server.servlet.context-path=/api
spring.application.name=payment-service

# Database Configuration
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/payment_db
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
